export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  BRANCHES: '/branches',
  DEPARTMENTS: '/departments',
  CLASSROOMS: '/classrooms',
  LEVELS: '/levels',
  CHILDREN: '/children',
  CHILDREN_CREATE: '/children/create',
  childDetail: (id: string) => `/children/${id}`,
  childEdit: (id: string) => `/children/${id}/edit`,
  CHILDREN_ARCHIVE: '/children/archive',
  CHILDREN_BIRTHDAYS: '/children/birthdays',
  BROTHERS: '/brothers',
  GRADUATION: '/graduation',
  TEACHERS: '/teachers',
  WORKERS: '/workers',
  ATTENDANCE: '/attendance',
  ABSENCE: '/absence',
  DEPARTURE: '/departure',
  EVALUATIONS: '/evaluations',
  EVALUATIONS_WINNERS: '/evaluations/winners',
  SUBSCRIPTIONS: '/subscriptions',
  CHILDREN_SUBSCRIPTION_INFO: '/children-subscription-info', // جديد
  TREASURY: '/treasury',
  SALARIES: '/salaries',
  BUSES: '/buses',
  DRIVERS: '/drivers',
  CHILD_ASSESSMENT: '/child-assessment',
  MESSAGE_ARCHIVE: '/message-archive',
  REGISTERS_OPERATION: '/registers-operation',
  USERS: '/users',
  SETTINGS: '/settings',
  FORBIDDEN: '/403',
  NOT_FOUND: '/404',
} as const;